### ISSUE TITLE
Refactor index.html to include a list/table of all kinds of resources

### ISSUE THREAD

**Issue by groovecoder** [mozilla/tracking-test#3]
The index page could show a table/list of all the different kinds of tracking resources - i.e., base, ads, analytics, social, full/strict, cryptomining, fingerprinting - with an indicator next to each showing whether it was blocked or not.

**Comment by englehardt** [comment]
This would be easy to build if we fix https://github.com/mozilla-services/shavar-prod-lists/issues/49. Once we have those domains we can add a page to each subdomain that allows us to query whether the list is active (similar to https://github.com/mozilla/trackertest/blob/master/cookie_access_test.html).
