### ISSUE TITLE
Full.html test page is no longer correct

### ISSUE THREAD

**Issue by rbillings** [mozilla/tracking-test#7]
https://github.com/mozilla/tracking-test/commit/db988da6c66a6665ec0b4a22daa9476acbfc98b4#commitcomment-32307000

**Comment by rpappalax** [comment]
@groovecoder I'm seeing the same thing.  What does the full page test provide that the other test pages do not?  Is it a combination of tests altogether?

**Comment by groovecoder** [comment]
302 @englehardt

**Comment by englehardt** [comment]
I think "full" is referring to a test page for the tracking protection list that contains the Content category. This page tests a gravatar resource, which is on the Content category.

**Comment by rpappalax** [comment]
> I think "full" is referring to a test page for the tracking protection list that contains the Content category. This page tests a gravatar resource, which is on the Content category.

@englehardt thanks for the clarification.  Since we don't have a more detailed README at the moment, would it make sense if we renamed this page content.html? (since all the other pages seem to reflect the category they are testing by name)

**Comment by englehardt** [comment]
@rpappalax that makes sense to me. Note that Francois' comments on the test pages being broken still stand (so we should file a separate issue for the renaming).
